language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.2
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
  - jruby
  - rbx-head
matrix:
  allow_failures:
    - rvm: 1.8.7
script: ruby test/test_ruby-mp3info.rb
